---
- name: Install httpd and geting it running
  hosts: all
  become: root
  tasks:
    - package: "name=httpd state=present"
    - copy: "src=home.html dest=/var/www/html/"
    - service: "name=httpd state: started"
